<?php

if (!defined('_ECRIRE_INC_VERSION')) {
	return;
}

/**
 * Définitions CLI propres au module, extraites du registre historique.
 */
function association_adhesions_config_cli_definitions() {
	return [
		'adhesion.cotisations_multidevises' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_cotisations_multidevises',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'non',
			'description' => 'Configuration Association : adhesion.cotisations_multidevises.',
		],
		'adhesion.validite' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/validite',
			'allowed' => [
				0 => 'scolaire',
				1 => 'annee',
			],
			'default' => 'scolaire',
			'description' => 'Configuration Association : adhesion.validite.',
		],
		'adhesion.date_scolaire_suivante' => [
			'type' => 'day_month',
			'writable' => true,
			'path' => '/association_metas/date_scolaire_suivante',
			'default' => '01/06',
			'description' => 'Configuration Association : adhesion.date_scolaire_suivante.',
		],
		'adhesion.date_scolaire_nouvelle' => [
			'type' => 'day_month',
			'writable' => true,
			'path' => '/association_metas/date_scolaire_nouvelle',
			'default' => '30/09',
			'description' => 'Configuration Association : adhesion.date_scolaire_nouvelle.',
		],
		'adhesion.compte_secondaire' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/config_compte_secondaire',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'non',
			'description' => 'Configuration Association : adhesion.compte_secondaire.',
		],
		'adhesion.compte_secondaire_activation' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/config_compte_secondaire_activation',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'non',
			'description' => 'Configuration Association : adhesion.compte_secondaire_activation.',
		],
		'adhesion.age_limite_enfants' => [
			'type' => 'integer',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_age_limit_enfants',
			'default' => '',
			'min' => 0,
			'max' => 150,
			'description' => 'Configuration Association : adhesion.age_limite_enfants.',
			'allow_empty' => true,
		],
		'adhesion.carte_adherent' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_carte_adherent',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'non',
			'description' => 'Configuration Association : adhesion.carte_adherent.',
		],
		'adhesion.zones' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/zone_adherent',
			'default' => [],
			'description' => 'Configuration Association : adhesion.zones.',
		],
		'adhesion.listes_diffusion' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/liste_diffusion',
			'default' => [],
			'description' => 'Configuration Association : adhesion.listes_diffusion.',
		],
		'adhesion.donation' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_donation',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'non',
			'description' => 'Configuration Association : adhesion.donation.',
		],
		'adhesion.donation_defaut' => [
			'type' => 'decimal',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_donation_defaut',
			'default' => '',
			'description' => 'Configuration Association : adhesion.donation_defaut.',
			'min' => 0,
			'max' => 100000000,
			'allow_empty' => true,
		],
		'adhesion.pages_modalites_inscription' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/pages_modalite_inscription',
			'default' => [],
			'description' => 'Configuration Association : adhesion.pages_modalites_inscription.',
		],
		'adhesion.pages_modalites_evenement' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/pages_modalite_evenement',
			'default' => [],
			'description' => 'Configuration Association : adhesion.pages_modalites_evenement.',
		],
		'adhesion.recu_paiement' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_envoi_recu_paiement_adhesion',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'non',
			'description' => 'Configuration Association : adhesion.recu_paiement.',
		],
		'adhesion.recu_paiement_cc' => [
			'type' => 'email_list',
			'writable' => true,
			'path' => '/association_metas/config_envoi_recu_adhesion_cc',
			'default' => '',
			'description' => 'Configuration Association : adhesion.recu_paiement_cc.',
			'max_length' => 2000,
		],
		'adhesion.notification_validation_paiement' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_envoi_validation_paiement_adhesion',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'oui',
			'description' => 'Configuration Association : adhesion.notification_validation_paiement.',
		],
		'adhesion.notification_echeance' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/notification_adherent_echu',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'oui',
			'description' => 'Configuration Association : adhesion.notification_echeance.',
		],
		'adhesion.echeances_notification' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/notification_echeance_cotisation',
			'default' => [],
			'description' => 'Configuration Association : adhesion.echeances_notification.',
			'allowed' => [
				0 => '60',
				1 => '30',
				2 => '15',
				3 => '7',
			],
		],
		'adhesion.destinataires_creation_cotisation' => [
			'type' => 'email_list',
			'writable' => true,
			'path' => '/association_metas/config_destinataires_creation_cotisation_tresorier',
			'default' => '',
			'description' => 'Configuration Association : adhesion.destinataires_creation_cotisation.',
			'max_length' => 2000,
		],
		'entreprise.validite' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/validite_entreprise',
			'allowed' => [
				0 => 'scolaire',
				1 => 'annee',
			],
			'default' => 'scolaire',
			'description' => 'Configuration Association : entreprise.validite.',
		],
		'entreprise.date_scolaire_suivante' => [
			'type' => 'day_month',
			'writable' => true,
			'path' => '/association_metas/date_scolaire_suivante_entreprise',
			'default' => '01/06',
			'description' => 'Configuration Association : entreprise.date_scolaire_suivante.',
		],
		'entreprise.date_scolaire_nouvelle' => [
			'type' => 'day_month',
			'writable' => true,
			'path' => '/association_metas/date_scolaire_nouvelle_entreprise',
			'default' => '30/09',
			'description' => 'Configuration Association : entreprise.date_scolaire_nouvelle.',
		],
		'entreprise.cotisation' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_cotisation_compte_entreprise',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'oui',
			'description' => 'Configuration Association : entreprise.cotisation.',
		],
		'entreprise.inscription_evenement' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_event_inscription_compte_entreprise',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'non',
			'description' => 'Configuration Association : entreprise.inscription_evenement.',
		],
		'entreprise.listes_diffusion' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_liste_diffusion_compte_entreprise',
			'default' => [],
			'description' => 'Configuration Association : entreprise.listes_diffusion.',
		],
		'entreprise.notification_echeance' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/notification_echeance_notifier_echu_entreprise',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'oui',
			'description' => 'Configuration Association : entreprise.notification_echeance.',
		],
		'entreprise.echeances_notification' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/notification_echeance_cotisation_entreprise',
			'default' => [],
			'description' => 'Configuration Association : entreprise.echeances_notification.',
			'allowed' => [
				0 => '60',
				1 => '30',
				2 => '15',
				3 => '7',
			],
		],
		'entreprise.destinataires_creation_cotisation' => [
			'type' => 'email_list',
			'writable' => true,
			'path' => '/association_metas/config_destinataires_creation_cotisation_tresorier_entreprise',
			'default' => '',
			'description' => 'Configuration Association : entreprise.destinataires_creation_cotisation.',
			'max_length' => 2000,
		],
		'affichage.public_filtres_annuaire' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/config_filtres_annuaire',
			'default' => [],
			'description' => 'Configuration Association : affichage.public_filtres_annuaire.',
			'allowed' => [
				0 => 'code_postal',
				1 => 'quartier',
				2 => 'ville',
			],
		],
		'affichage.prive_filtres_adherents' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/config_champs_filtres_adherents',
			'default' => [],
			'description' => 'Configuration Association : affichage.prive_filtres_adherents.',
		],
		'affichage.prive_colonnes_adherents' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/config_champs_colonnes_adherents',
			'default' => [],
			'description' => 'Configuration Association : affichage.prive_colonnes_adherents.',
		],
		'modules.gis_email' => [
			'type' => 'email_list',
			'writable' => true,
			'path' => '/association_metas/notification_gis_config_email',
			'default' => '',
			'description' => 'Configuration Association : modules.gis_email.',
			'max_length' => 1000,
		],
		'modules.gis_actions' => [
			'type' => 'list',
			'writable' => true,
			'path' => '/association_metas/notification_gis_config_action',
			'default' => [],
			'description' => 'Configuration Association : modules.gis_actions.',
			'allowed' => [
				0 => 'modification_adherent',
				1 => 'echec_adherent',
			],
		],
		'maintenance.jours_inactivite' => [
			'type' => 'integer',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_maintenance_jours_inactivite',
			'default' => '365',
			'min' => 0,
			'max' => 36500,
			'description' => 'Configuration Association : maintenance.jours_inactivite.',
		],
		'maintenance.supprimer_auteurs_sans_paiements' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_maintenance_supprimer_auteurs_sans_paiements',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'oui',
			'description' => 'Configuration Association : maintenance.supprimer_auteurs_sans_paiements.',
		],
		'maintenance.anonymiser_auteurs_avec_paiements' => [
			'type' => 'enum',
			'writable' => true,
			'path' => '/association_metas/meta_cfg_maintenance_anonymiser_auteurs_avec_paiements',
			'allowed' => [
				0 => 'oui',
				1 => 'non',
			],
			'default' => 'oui',
			'description' => 'Configuration Association : maintenance.anonymiser_auteurs_avec_paiements.',
		],
	];
}
